# The URL the site will be built for
base_url = "https://helix-editor.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generate an RSS feed
generate_feed = true

# The site title, author and description; used in feeds by default.
title = "Helix"
description = "A post-modern modal text editor."
author = "Helix Contributors"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
